#!/bin/bash

world_offset=3EA7A7
world_binary=WorldServer
world_folder=WorldServer

zone_offset=822D47
zone_binary=ZoneServer
zone_folder=ZoneServer

case "$1" in
full)
	host_ip=$(ip a | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')
	if [ "$host_ip" != "" ]; then
		echo -e "Select IP Option:\n1 - Use Current IP: $host_ip\n2 - Input Other IP"
		read invar
	else
		invar="2"
	fi
	if [ "$invar" = "2" ]; then
		echo "Please Enter IP:"
		read host_ip
	fi

	echo "Please Enter PostgreSQL Password:"
	read db_pwd

	ip_parts=(${host_ip//./ })
	ip_parts[3]=0
	server_ip="${ip_parts[0]}.${ip_parts[1]}.${ip_parts[2]}.${ip_parts[3]}"

	hex_ip=""

	for char in $(echo "$server_ip" | grep -o .); do
		hex_ip+=$(printf '%02x' "'$char")
	done

	hex_ip+="000000"

	ip_bytes=$(echo $hex_ip | sed 's/\(..\)/\\\x\1/g')

	cp ${world_folder}/${world_binary} ${world_folder}/${world_binary}.bak

	echo -en $ip_bytes | dd of=${world_folder}/${world_binary} bs=1 seek=$((0x$world_offset)) count=${#ip_bytes} conv=notrunc >/dev/null 2>&1

	cp ${zone_folder}/${zone_binary} ${zone_folder}/${zone_binary}.bak

	echo -en $ip_bytes | dd of=${zone_folder}/${zone_binary} bs=1 seek=$((0x$zone_offset)) count=${#ip_bytes} conv=notrunc >/dev/null 2>&1

	sed -i "s/db_pwd/$db_pwd/g" "./setup.ini"
	sed -i "s/db_pwd/$db_pwd/g" "./GatewayServer/setup.ini"

	wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
	echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list >/dev/null
	sudo apt-get update -y
	sudo apt -y install postgresql-12
	POSTGRESQLVERSION=$(psql --version | cut -c 19-20)

	cd "/etc/postgresql/$POSTGRESQLVERSION/main"
	sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" postgresql.conf
	sed -i "s+host    all             all             127.0.0.1/32            md5+host    all             all             0.0.0.0/0            md5+g" pg_hba.conf

	sudo -u postgres psql -c "ALTER user postgres WITH password '$db_pwd';"

	service postgresql restart

	chmod 777 /root -R

	sudo -u postgres psql -c "create database gf_gs encoding 'UTF8' template template0;"
	sudo -u postgres psql -c "create database gf_ls encoding 'UTF8' template template0;"
	sudo -u postgres psql -c "create database gf_ms encoding 'UTF8' template template0;"
	sudo -u postgres psql -d gf_gs -c "\i '/root/gf_server/SQL/GF_GS.sql';"
	sudo -u postgres psql -d gf_ls -c "\i '/root/gf_server/SQL/GF_LS.sql';"
	sudo -u postgres psql -d gf_ms -c "\i '/root/gf_server/SQL/GF_MS.sql';"
	sudo -u postgres psql -d gf_ls -c "UPDATE worlds SET ip = '$host_ip';"
	sudo -u postgres psql -d gf_gs -c "UPDATE serverstatus SET ext_address = '$host_ip' WHERE ext_address != 'none';"

	;;
update)
	host_ip=$(ip a | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')
	if [ "$host_ip" != "" ]; then
		echo -e "Select IP Option:\n1 - Use Current IP: $host_ip\n2 - Input Other IP"
		read invar
	else
		invar="2"
	fi
	if [ "$invar" = "2" ]; then
		echo "Please Enter IP:"
		read host_ip
	fi

	ip_parts=(${host_ip//./ })
	ip_parts[3]=0
	server_ip="${ip_parts[0]}.${ip_parts[1]}.${ip_parts[2]}.${ip_parts[3]}"

	hex_ip=""

	for char in $(echo "$server_ip" | grep -o .); do
		hex_ip+=$(printf '%02x' "'$char")
	done

	hex_ip+="000000"

	ip_bytes=$(echo $hex_ip | sed 's/\(..\)/\\\x\1/g')

	cp ${world_folder}/${world_binary} ${world_folder}/${world_binary}.bak

	echo -en $ip_bytes | dd of=${world_folder}/${world_binary} bs=1 seek=$((0x$world_offset)) count=${#ip_bytes} conv=notrunc >/dev/null 2>&1

	cp ${zone_folder}/${zone_binary} ${zone_folder}/${zone_binary}.bak

	echo -en $ip_bytes | dd of=${zone_folder}/${zone_binary} bs=1 seek=$((0x$zone_offset)) count=${#ip_bytes} conv=notrunc >/dev/null 2>&1

	sudo -u postgres psql -d gf_ls -c "UPDATE worlds SET ip = '$host_ip';"
	sudo -u postgres psql -d gf_gs -c "UPDATE serverstatus SET ext_address = '$host_ip' WHERE ext_address != 'none';"

	;;
restore)
	host_ip=$(ip a | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')
	if [ "$host_ip" != "" ]; then
		echo -e "Select IP Option:\n1 - Use Current IP: $host_ip\n2 - Input Other IP"
		read invar
	else
		invar="2"
	fi
	if [ "$invar" = "2" ]; then
		echo "Please Enter IP:"
		read host_ip
	fi

	sudo -u postgres psql -c "DROP DATABASE gf_gs;"
	sudo -u postgres psql -c "DROP DATABASE gf_ls;"
	sudo -u postgres psql -c "DROP DATABASE gf_ms;"

	if ! [ $(sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='gf_gs'") ] && ! [ $(sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='gf_ls'") ] && ! [ $(sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='gf_ms'") ]; then
		chmod 777 /root -R
		sudo -u postgres psql -c "create database gf_gs encoding 'UTF8' template template0;"
		sudo -u postgres psql -c "create database gf_ls encoding 'UTF8' template template0;"
		sudo -u postgres psql -c "create database gf_ms encoding 'UTF8' template template0;"
		sudo -u postgres psql -d gf_gs -c "\i '/root/gf_server/SQL/GF_GS.sql';"
		sudo -u postgres psql -d gf_ls -c "\i '/root/gf_server/SQL/GF_LS.sql';"
		sudo -u postgres psql -d gf_ms -c "\i '/root/gf_server/SQL/GF_MS.sql';"
		sudo -u postgres psql -d gf_ls -c "UPDATE worlds SET ip = '$host_ip';"
		sudo -u postgres psql -d gf_gs -c "UPDATE serverstatus SET ext_address = '$host_ip' WHERE ext_address != 'none';"
	else
		echo $R"Close All DB Connections!"$W
	fi

	;;
register)
	sudo apt-get install apache2 -y
    sudo apt-get install php -y
    sudo apt-get install php-cli -y
    sudo apt-get install php-pgsql -y

	echo "Please Enter PostgreSQL Password:"
	read db_pwd

	sudo cp ./_utils/register.php /var/www/html

	sed -i "s/db_pwd/$db_pwd/g" "/var/www/html/register.php"

	;;

*)
	echo "Usage: $0 {full|update|restore|register}"
	echo "full - Full Server Instalation"
	echo "update - Server IP Update"
	echo "restore - Delete And Create DB"
	echo "register - Install Registration"
	exit 1
	;;
esac
